name: day2

description: A Flutter shop app with basic navigation and a static product list.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  dartz: ^0.10.1
  kt_dart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.2
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  auto_route:  ^10.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  auto_route_generator: ^10.0.1
  

flutter:
  uses-material-design: true

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
